### ISSUE TITLE
使用Laravel6.0报错

### ISSUE THREAD

**Issue by yming** [xiaohuilam/laravel-wxapp-login#11]
Illuminate \ Contracts \ Container \ BindingResolutionException
Target class [wechat.mini_program] does not exist.
Previous exceptions
Class wechat.mini_program does not exist (-1)

不知跟版本有没有关系？

**Comment by xiaohuilam** [comment]
> Illuminate \ Contracts \ Container \ BindingResolutionException
> Target class [wechat.mini_program] does not exist.
> Previous exceptions
> Class wechat.mini_program does not exist (-1)
> 
> 不知跟版本有没有关系？

你在 php artisan tinker 看看
```php
app('wechat.mini_program')
```
能否输出 `EasyWeChat\MiniProgram\Application` 对象

**Comment by yming** [comment]
已经解决了，在config里面没有wechat.php，手动php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProvider" ，创建之后就可以了，谢谢

**Comment by yuzhewo** [comment]
打开wechat.php中的小程序配置就可以了
` /*
     * 小程序
     */
    'mini_program' => [
        'default' => [
            'app_id'  => env('WECHAT_MINI_PROGRAM_APPID', ''),
            'secret'  => env('WECHAT_MINI_PROGRAM_SECRET', ''),
            'token'   => env('WECHAT_MINI_PROGRAM_TOKEN', ''),
            'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', ''),
        ],
    ],`

**Comment by xiaohuilam** [comment]
> 打开wechat.php中的小程序配置就可以了 ` /* * 小程序 */ 'mini_program' => [ 'default' => [ 'app_id' => env('WECHAT_MINI_PROGRAM_APPID', ''), 'secret' => env('WECHAT_MINI_PROGRAM_SECRET', ''), 'token' => env('WECHAT_MINI_PROGRAM_TOKEN', ''), 'aes_key' => env('WECHAT_MINI_PROGRAM_AES_KEY', ''), ], ],`

https://github.com/xiaohuilam/laravel-wxapp-login/commit/2e6218523b631519eebddc606cf16e3a5b47a46e 已更新到readme，感谢提供此关键信息
