### ISSUE TITLE
安装出现错误

### ISSUE THREAD

**Issue by Hermit503** [xiaohuilam/laravel-wxapp-login#6]
In RouteFileRegistrar.php line 35:

  Illuminate\Routing\RouteFileRegistrar::register(): Failed opening required
  '/home/vagrant/code/saftyLab/routes/wechat.php' (include_path='.:/usr/share
  /php')

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
Installation failed, reverting ./composer.json to its original content.

**Comment by xiaohuilam** [comment]
fixed, try ver `>=0.9`
